# Site settings
author: Ramon Chavez
title: How much fun I had building my own Ruby gem.
header-img: img/home-bg.png
email: rachavez1974@gmail.com
copyright_name: Ramon Chavez
description: > # this means to ignore newlines until "baseurl:"
  Ruby is awesome.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rachavez1974

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
